/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejemplo_jtable_seleccionable;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Walter Gdmz
 */
public class jTabla extends javax.swing.JFrame {

    /**
     * Creates new form jTabla
     */
    public jTabla() {
        initComponents();
        //Titulo del Jframe
        setTitle("Tabla Producto");
        //Centrar el jFrame en pantalla
        setLocationRelativeTo(null);
        
        
        Producto p = new Producto();
        p.setId_producto(25);
        p.setNombre_producto("Bebida Enlatada");
        p.setPrecio_Producto(0.50);
        p.setCantidad_producto(150);
        
        Producto p2 = new Producto();
        p2.setId_producto(35);
        p2.setNombre_producto("Galletas");
        p2.setPrecio_Producto(0.70);
        p2.setCantidad_producto(60);
        
        //Definimos los encabezados de las columnas
        String[] columnas = {"Id Producto","Nombre Producto","Precio Producto","Cantidad"};
        
        //Creamos el modela de la tabla le pasamos como parametro las columnas
        DefaultTableModel modeloTabla = new DefaultTableModel(null,columnas);
        
        //Definimos un arreglo tipo object sera la fila y cada indice una celda
        Object [] fila = new Object[4];
        fila[0] = p.getId_producto();
        fila[1] = p.getNombre_producto();
        fila[2] = p.getPrecio_Producto();
        fila[3] = p.getCantidad_producto();
        
        //Agregamos la fila al modelo con el metodo addRow
        modeloTabla.addRow(fila);
        
        Object [] fila2 = new Object[4];
        fila2[0] = p2.getId_producto();
        fila2[1] = p2.getNombre_producto();
        fila2[2] = p2.getPrecio_Producto();
        fila2[3] = p2.getCantidad_producto();
        
        modeloTabla.addRow(fila2);
        
        //Pasamos el modelo al Jtable con el metodo setModel para que lo muestre
        jTable1.setModel(modeloTabla);
        
       
    }
    // ===============================================================
    // ===============================================================
    //Metodo para llenar los jTextBox con los datos de la tabla
    public void llenar(){
        //Guardamos el valor de la fila seleccionada
        int fila = this.jTable1.getSelectedRow();
        //El numero de la columna aumentara segun corresponda al jTextBox
        int columna = 0;
        //Asignamos al jTextBox la celda y hacemos un parseo a string con el metodo valueOf()
        // y el metodo getValueAt()
        this.jTextId_producto.setText(String.valueOf(this.jTable1.getValueAt(fila, columna++)));
        this.jTextNombre_producto.setText(String.valueOf(this.jTable1.getValueAt(fila, columna++)));
        this.jTextPrecio_producto.setText(String.valueOf(this.jTable1.getValueAt(fila, columna++)));
        this.jTextCantidad.setText(String.valueOf(this.jTable1.getValueAt(fila, columna)));
    }
    
    // ===============================================================
    // ===============================================================

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextId_producto = new javax.swing.JTextField();
        jTextNombre_producto = new javax.swing.JTextField();
        jTextPrecio_producto = new javax.swing.JTextField();
        jTextCantidad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("ID PRODUCTO");

        jLabel2.setText("NOMBRE PRODUCTO");

        jLabel3.setText("PRECIO PRODUCTO");

        jLabel4.setText("CANTIDAD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jTextId_producto, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jTextCantidad)
                    .addComponent(jTextNombre_producto)
                    .addComponent(jTextPrecio_producto))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextId_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextNombre_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTextPrecio_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTextCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        // ===============================================================
        // ===============================================================
        //Llamada al metodo llenar 
        llenar();
        
        // ===============================================================
        // ===============================================================
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jTabla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextCantidad;
    private javax.swing.JTextField jTextId_producto;
    private javax.swing.JTextField jTextNombre_producto;
    private javax.swing.JTextField jTextPrecio_producto;
    // End of variables declaration//GEN-END:variables
}
